name: Build LaTeX

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: bign.tex
          working_directory: spec/
          args: -jobname=bign -pdf -file-line-error -halt-on-error -interaction=nonstopmode
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: bign
          path: spec/bign.pdf